---
- name: Check if docker is installed
  command: "docker -v"
  register: is_docker_installed
  failed_when: is_docker_installed.rc < 0
  changed_when: false

- name: Install Docker CE
  block:
    - name: ensure required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker’s official GPG key
      apt_key:
        id: 0EBFCD88
        url: http://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add the docker package repositry into source list
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_lsb.codename}} stable"
        state: present

    - name: install docker ce
      apt:
        name: docker-ce
        update_cache: no
        state: latest

    - name: Download Dependence Ansible Docker module
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /home/ubuntu/get-pip.py
        mode: 0755

    - name: Install pip
      shell: python get-pip.py
      args:
        chdir: /home/ubuntu/
      become: true

    - name: Install docker-py module
      pip:
        name: docker-py

  when: is_docker_installed.rc > 0
  tags:
    - docker


- name: start docker
  service:
    name: docker
    state: started
