---
- name: setup registry container
  docker_container:
    name: local_registry
    hostname: localhost
    state: started
    restart_policy: always
    image: registry
    ports:
      - 5000:5000